name: test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          tar -xvf gettext.tar
          sudo cp inst/bin/xgettext /usr/sbin/
          sudo cp inst/lib/* /usr/lib/
          xgettext --no-wrap -L Python --from-code=UTF-8 -kpgettext:1c,2 --add-comments="TRANSLATORS:" -d enigma2 -s -o test.pot test.py
          cat test.pot
