name: test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          tar -xvf gettext.tar
          sudo cp inst/bin/xgettext /usr/sbin/
          rm -rf inst/lib/gettext
          sudo cp inst/lib/* /usr/lib/
          xgettext -V
